server:
  port: 8762
  servlet:
    context-path: /eureka-server
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: eureka-server
  jmx:
    enabled: false

eureka:
  instance:
    hostname: 127.0.0.1
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
  server:
    enable-self-preservation: false
