server:
  port: 9999
spring:
  application:
    name: multiple-data-source-dynamic
  datasource:
    master:
      name: mysql-db1
      type: com.zaxxer.hikari.HikariDataSource
      jdbc-url: jdbc:mysql://127.0.0.1:3306/test1?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: jianbo@feng.0825
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        minimum-idle: 10
        maximum-pool-size: 60
        auto-commit: true
        idle-timeout: 60000
        pool-name: InsectControlHikariCP
        max-lifetime: 60000
        connection-timeout: 60000
        connection-test-query: SELECT 1
        validation-timeout: 3000
        login-timeout: 5
        read-only: false
    cluster:
      name: mysql-db2
      type: com.zaxxer.hikari.HikariDataSource
      jdbc-url: jdbc:mysql://127.0.0.1:3306/test2?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
      username: root
      password: jianbo@feng.0825
      driver-class-name: com.mysql.cj.jdbc.Driver
      hikari:
        minimum-idle: 10
        maximum-pool-size: 60
        auto-commit: true
        idle-timeout: 60000
        pool-name: InsectControlHikariCP
        max-lifetime: 60000
        connection-timeout: 60000
        connection-test-query: SELECT 1
        validation-timeout: 3000
        login-timeout: 5
        read-only: false
  output:
    ansi:
      enabled: always # 彩色日志设置
mybatis:
  master:
    mapper-locations: classpath:mapper/master/*.xml
    type-aliases-package: com.feng.datasource.multiple.dynamic.entity
    configuration: # mybatis全局配置
      cache-enabled: true
      local-cache-scope: session
  cluster:
    mapper-locations: classpath:mapper/cluster/*.xml
    type-aliases-package: com.feng.datasource.multiple.dynamic.entity
    configuration: # mybatis全局配置
      cache-enabled: true
      local-cache-scope: session

logging:
  level:
    com:
      feng:
        datasource:
          multiple:
            dynamic: debug
