server:
  port: 8077
spring:
  thymeleaf:
    prefix: classpath:/templates/
  mail:
    host: smtp.qq.com
    username: 445121408
    default-encoding: utf-8
    # QQ邮箱需要使用授权码 @see https://jingyan.baidu.com/article/4f7d5712b1ac7c1a201927da.html
    password: lpryaaaulvfqbhee
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    #配置数据源
    datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost:5432/quartz
      username: postgres
      password: postgres
    quartz:
      #持久化到数据库方式
#      job-store-type: jdbc
#      initialize-schema: always
      properties:
        org:
          quartz:
            scheduler:
              instanceName: MyScheduler
              instanceId: AUTO
#            jobStore:
#              class: org.quartz.impl.jdbcjobstore.JobStoreTX
#              driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
#              tablePrefix: quartz.QRTZ_
#              isClustered: true
#              clusterCheckinInterval: 10000
#              useProperties: false
            threadPool:
              class: org.quartz.simpl.SimpleThreadPool
              threadCount: 15
              threadPriority: 5
              threadsInheritContextClassLoaderOfInitializingThread: true

  jpa:
    generate-ddl: false
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      # 不设置懒加载
      #(以免出现异常org.hibernate.LazyInitializationException: could not initialize proxy - no Session
      #  ==>https://blog.csdn.net/pangyazhou/article/details/83447599)
      hibernate.enable_lazy_load_no_trans: true
#  datasource:
#    platform: h2
#    schema: classpath*:schema.sql
#    data: classpath*:data.sql


logging:
  level:
    root: INFO
    org:
      springframework:
        security: DEBUG
        web: ERROR
      hibernate: DEBUG
      apache:
        commons:
          dbcp2: DEBUG
    com:
      feng:
        springboot:
          websocket: DEBUG

  file:
    name: mylogFile.log
    path: concretepage/logs
#  pattern:
#    console: %d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n
#    file: %d{yyyy-MMM-dd HH:mm:ss.SSS} %-5level [%thread] %logger{15} - %msg%n
