spring:
  datasource:
    #  url: jdbc:mysql://127.0.0.1:3306/activiti-designer?useSSL=false&amp;useUnicode=true&amp;characterEncoding=UTF-8&amp;zeroDateTimeBehavior=convertToNull
    url: jdbc:mysql://127.0.0.1:3306/activiti7?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true&nullCatalogMeansCurrent=true
    username: root
    password: jianbo@feng.0825
    driver-class-name: com.mysql.cj.jdbc.Driver
    #  password: root
    #  driver-class-name: com.mysql.jdbc.Driver
    thymeleaf:
      mode: LEGACYHTML5
      cache: false
    type: com.alibaba.druid.pool.DruidDataSource

  activiti:
    database-schema: activiti7
    check-process-definitions: true
    database-schema-update: true
    process-definition-location-prefix: classpath:/processes/
#    history-level: full
#    db-history-used: true
#    db-identity-used: true
  liquibase:
    enabled: false
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

security:
  basic:
    enabled: false
server:
  port: 8093
