# 服务器配置
server:
    port: 8090
# logback日志配置
logging:
    config: classpath:log/logback-spring.xml
    level:
        root: INFO
        org.springframework.web: INFO
        org.springframework.security: INFO
#    file:
#        path: log

# Spring配置
spring:
    # 多环境配置
    profiles:
        # 如不指定默认application.yml节点，指定后运行指定配置文件配置
        active:
    # 数据源配置
    datasource:
        username: root
        password: jianbo@feng.0825
        # 注意时区
        url: jdbc:mysql://127.0.0.1:3306/redis-websocket?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=UTF-8&allowMultiQueries=true
        driver-class-name: com.mysql.cj.jdbc.Driver
    # 模板引擎
    freemarker:
        #内容格式
        content-type: text/html
        #缓存配置
        cache: false
        #模板路径
        template-loader-path: classpath:/templates
        #编码格式
        charset: UTF-8
        #是否启用
        enabled: true
        #请求内容属性
        request-context-attribute: request
        expose-request-attributes: true
        expose-session-attributes: true
        #检查模板路径
        check-template-location: true
        #文件后缀
        suffix: .ftl
    # Redis配置
    redis:
        database: 3
        host: 127.0.0.1
        port: 6379
        password:
        jedis:
            pool:
                max-active: 8
                max-idle: 8
                max-wait: -1ms
                min-idle: 0
        timeout: 600
