spring:
  #配置数据源
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/quartz
    username: postgres
    password: postgres
  quartz:
    #持久化到数据库方式
    job-store-type: jdbc
    initialize-schema: always
    properties:
      org:
        quartz:
          scheduler:
            instanceName: MyScheduler
            instanceId: AUTO
          jobStore:
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            driverDelegateClass: org.quartz.impl.jdbcjobstore.PostgreSQLDelegate
            tablePrefix: quartz.QRTZ_
            isClustered: true
            clusterCheckinInterval: 10000
            useProperties: false
          threadPool:
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 10
            threadPriority: 5
            threadsInheritContextClassLoaderOfInitializingThread: true

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.songguoliang.springboot.entity
  configuration: # mybatis全局配置
    cache-enabled: true
    local-cache-scope: session

#logging:
#  level:
#    com:
#      insectcontrol:
#        repository: debug
#  #   com.insectcontrol.repository : debug



#pagehelper
pagehelper:
  helperDialect: postgresql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check
server:
  port: 8083
  servlet:
    context-path: /quartz-db