spring:
  application:
    name: springboot-elasticsearch
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-name: elasticsearch
    # 集群配置
    #  cluster-nodes: 192.168.1.103:9300,192.168.1.103:9500
    # 单台配置
      cluster-nodes: 127.0.0.1:9300

server:
  port: 9996

logging:
  level:
    com:
      feng:
        elasticsearch: debug
