spring:
  application:
    name: springboot-elasticsearch
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-name: elasticsearch
      cluster-nodes: 192.168.1.103:9300,192.168.1.103:9500

server:
  port: 9996

#elasticsearch:
#  cluster-name: elasticsearch
#  host: 127.0.0.1
#  port: 9300
#  pool: 5
logging:
  level:
    com:
      feng:
        elasticsearch: debug
