spring:
  application:
    name: springboot2-redis-cluster
server:
  port: 9995
redis:
  nodes: 127.0.0.1:26379,127.0.0.1:26382,127.0.0.1:26383
  masterName: mymaster
  password:
  maxTotal: 10000
  maxIdle: 100
  minIdle: 50
  timeout: 30000

