spring:
  #配置数据源
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/quartz
    username: postgres
    password: postgres
  quartz:
    #持久化到数据库方式
    job-store-type: jdbc
    initialize-schema: always

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.feng.quartz.entity
  configuration: # mybatis全局配置
    cache-enabled: true
    local-cache-scope: session

#logging:
#  level:
#    com:
#      insectcontrol:
#        repository: debug
#  #   com.insectcontrol.repository : debug



#pagehelper
pagehelper:
  helperDialect: postgresql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
  returnPageInfo: check
server:
  port: 8084
  servlet:
    context-path: /quartz-db
