

application:
  name: springboot-task-redis-01
spring:
  redis:
    database: 2
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 8
        min-idle: 0
        max-wait: -1
        max-idle: 8
    timeout: 3000
  data:
    redis:
      repositories:
        enabled: true
server:
  port: 9997
